# Generated by Django 6.1.1 on 2026-09-30 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0002_paymentschedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='apartment',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='building_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='city',
            field=models.CharField(default='Toshkent', max_length=100),
        ),
        migrations.AddField(
            model_name='apartment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='district',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='has_air_conditioner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartment',
            name='has_balcony',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartment',
            name='has_elevator',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='has_furniture',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartment',
            name='has_parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartment',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Kvartira'), ('penthouse', 'Penthouse'), ('studio', 'Studio')], default='apartment', max_length=20),
        ),
        migrations.AddField(
            model_name='apartment',
            name='renovation',
            field=models.CharField(blank=True, choices=[('new', 'Yangi ta’mir'), ('renovated', 'Ta’mirlangan'), ('whitebox', 'White Box'), ('blackbox', 'Qora suvoq'), ('none', 'Ta’mirsiz')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='total_floors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='square_meters',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.CreateModel(
            name='ApartmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='apartments/images/')),
                ('is_main', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='realestate.apartment')),
            ],
            options={
                'ordering': ['-is_main', 'id'],
            },
        ),
    ]
