# Generated by Django 6.1.1 on 2026-09-30 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0005_auditlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ('-created_at',), 'verbose_name': 'Audit log', 'verbose_name_plural': 'Audit logs'},
        ),
    ]
