# Generated by Django 6.1.1 on 2026-09-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0006_alter_auditlog_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentimage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartmentimage',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
